#!/usr/bin/env bash
set -euo pipefail

cd /workspace

git clone https://github.com/comfyanonymous/ComfyUI.git
cd ComfyUI

# 2. Install PyTorch
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
pip install -r requirements.txt
