#!/usr/bin/env bash
set -euo pipefail

cd /workspace/ComfyUI

huggingface-cli download Comfy-Org/flux1-dev flux1-dev.safetensors --local-dir models/diffusion_models
huggingface-cli download comfyanonymous/flux_text_encoders clip_l.safetensors --local-dir models/text_encoders
huggingface-cli download comfyanonymous/flux_text_encoders t5xxl_fp16.safetensors --local-dir models/text_encoders
huggingface-cli download Comfy-Org/Lumina_Image_2.0_Repackaged split_files/vae/ae.safetensors --local-dir models/vae
mv models/vae/split_files/vae/ae.safetensors models/vae/
rm -rf models/vae/split_files

# Download upscaler models
huggingface-cli download lllyasviel/Annotators RealESRGAN_x4plus.pth --local-dir models/upscale_models


# Download FLUX.1 Kontext model
huggingface-cli download Comfy-Org/flux1-kontext-dev_ComfyUI split_files/diffusion_models/flux1-dev-kontext_fp8_scaled.safetensors --local-dir models/diffusion_models
mv models/diffusion_models/split_files/diffusion_models/flux1-dev-kontext_fp8_scaled.safetensors models/diffusion_models/
rm -rf models/diffusion_models/split_files
